### ISSUE TITLE
Use of open data format

### ISSUE THREAD

**Issue by karelin** [MVC-Datasets/MVC#1]
Hi there,

Have you considered using some open format (such as zipped `CSV` or zipped `JSON`, or `HDF`) instead of `MAT` files. Not everyone have access to MATLAB and loading by 3rd-party tools can be difficult.

**Comment by MVC-Datasets** [comment]
Hi @karelin ,
Thanks for informing me of it.
I updated the github page and uploaded the json files [here](https://drive.google.com/open?id=0B0oMjGuurWR4ZVZ1X19veUkxeU0)

**Comment by appierys** [comment]
@MVC-Datasets Hello, I am trying to decode the `mvc_info.json` and encounter the following error:
```python
result = json.load(open('mvc_info.json'))
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 57753349: invalid start byte
```

**Comment by timh20022002** [comment]
Hi @appierys,

Sorry about this.  
We fixed the decoding issue, please download it again via [here](https://drive.google.com/open?id=0B0oMjGuurWR4ZVZ1X19veUkxeU0)
cheers,

**Comment by rojinsafavi** [comment]
Could you elaborate on how one can download the file with the jason?
