### ISSUE TITLE
[Question] Attribute Information

### ISSUE THREAD

**Issue by yukioichida** [MVC-Datasets/MVC#5]
Hi guys,

First, nice work, this dataset contains a huge set of annotations useful in my ontology research.

Have you a documentation that explain each attribute? I know that some attributes name in JSON file  are intuitive but i could not recognize the following attributes: fiftyU, hundred1U, hundred2U, hundred2O.

**Comment by timh20022002** [comment]
Hi yukioichida , 

The definition of these attributes is followed by Zappos.com.
FiftyU means the price is under $50, Hundred1U means the price is under $100, etc

quarterZip means quarter-zip closure, such as images below

![unnamed](https://user-images.githubusercontent.com/10151434/75636554-a697ce00-5c5a-11ea-82ba-6ee2389566f7.png)

quarter3zip means quarter-length zip with 3-Stripes, such as
![unnamed (1)](https://user-images.githubusercontent.com/10151434/75636564-b8797100-5c5a-11ea-9acc-475685ad1245.png)
![unnamed (2)](https://user-images.githubusercontent.com/10151434/75636565-badbcb00-5c5a-11ea-9bbb-4497b87c2e3a.png)

Cheers,

**Comment by yukioichida** [comment]
Thanks for the answer.
