### ISSUE TITLE
JSON link broke

### ISSUE THREAD

**Issue by PeterL1n** [MVC-Datasets/MVC#7]
Can't access the JSON version. The JSON download link requires permission.

Why not upload the JSON file directly to the git repo.

**Comment by timh20022002** [comment]
Upload a shared Link
https://drive.google.com/drive/folders/0B0oMjGuurWR4ZVZ1X19veUkxeU0?resourcekey=0-OGNzNY-DI4Tvg4ScQyaFBw&usp=sharing
